rest api
ochenmudro/DVOR pull request #1
Opened 2022-09-05 17:33 UTC by ochenmudro

2022-09-26 06:10 UTC, varya1441 requested changes

2022-09-26 06:10 UTC, varya1441 commented on src/main/java/com/example/demo/controller/ClientController.java
> +        if (clientId == null) return new ResponseEntity<>(HttpStatus.BAD_REQUEST);
add brackets
code is not readable

2022-09-26 06:10 UTC, varya1441 commented on src/main/java/com/example/demo/controller/ClientController.java
> +    @PutMapping(value = "attend/")
you dont need /

2022-09-26 06:10 UTC, varya1441 commented on src/main/java/com/example/demo/controller/ClientController.java
> +        if (clientId == null) return new ResponseEntity<>(HttpStatus.BAD_REQUEST);
in each if and for

2022-09-26 06:10 UTC, varya1441 commented on src/main/java/com/example/demo/job/JobService.java
> +    private static final Logger log = Logger.getLogger(JobService.class.getName());
better to put static final before constructor

2022-09-26 06:10 UTC, varya1441 commented on src/main/java/com/example/demo/job/StepProcessor.java
> +    public RepeatStatus execute(StepContribution contribution, ChunkContext chunkContext) throws Exception {
do you use it somewhere?

2022-09-26 06:10 UTC, varya1441 commented on src/main/java/com/example/demo/repository/ClientRepository.java
> +    //List<Client> getAllClientsByPageAndSize(Pageable pageable);
remove useless comments

2022-09-26 06:10 UTC, varya1441 commented on src/main/java/com/example/demo/repository/CoachRepository.java
> +
too much empty lines

2022-09-26 06:10 UTC, varya1441 commented on src/main/java/com/example/demo/repository/EventRepository.java
> +//    @Query(value = "SELECT * FROM event WHERE date_time > :today AND client_id = :clientId", nativeQuery = true)
remove useless comments

2022-09-26 06:10 UTC, varya1441 commented on src/main/java/com/example/demo/service/impl/ClientServiceImpl.java
> +
remove line

2022-09-26 06:10 UTC, varya1441 commented on src/main/java/com/example/demo/service/impl/ClientServiceImpl.java
> +//        List<Event> events = new ArrayList<>();
remove useless comments

2022-09-26 06:10 UTC, varya1441 commented on src/main/java/com/example/demo/service/impl/ClientServiceImpl.java
> +
empty method. do you need this?

2022-09-26 06:10 UTC, varya1441 commented on src/main/java/com/example/demo/service/impl/CoachServiceImpl.java
> +            sum += cost;
add brackets
code is not readable

2022-09-26 06:10 UTC, varya1441 commented on src/main/java/com/example/demo/service/impl/EventServiceImpl.java
> +
remove line

2022-09-26 09:32 UTC, ochenmudro commented on src/main/java/com/example/demo/job/StepProcessor.java
> +    public RepeatStatus execute(StepContribution contribution, ChunkContext chunkContext) throws Exception {
i think it uses when the step is built automatically

2022-09-27 15:50 UTC, varya1441 approved these changes

2022-09-28 07:07 UTC, merged